name: Collect news

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  push:
    paths:
      - ".github/workflows/collect.yml"
      - "collect.py"
      - "feeds.py"

permissions:
  contents: write

jobs:
  collect:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install feedparser python-dateutil

      - name: Run collector
        run: |
          echo "---- running collector"
          python collect.py
          echo "---- items.json summary"
          python - <<'PY'
          import json, pathlib
          p = pathlib.Path('items.json')
          d = json.loads(p.read_text(encoding='utf-8')) if p.exists() else {}
          items = d.get('items', [])
          sources = d.get('sources', [])
          print("items:", len(items))
          print("sources:", len(sources))
          print("updated_at:", d.get('updated_at'))
          PY

      - name: Commit items.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add items.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto update items.json"
            git push
          fi