name: Collect Eagles Feed

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: {}
  push:
    paths:
      - "feeds.py"
      - "collect.py"
      - ".github/workflows/collect.yml"

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run collector
        run: python collect.py
      - name: Commit & push items.json
        run: |
          if [[ -n "$(git status --porcelain items.json)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add items.json
            git commit -m "chore: update items.json ($(date -u +'%Y-%m-%d %H:%M:%SZ'))"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
