name: Collect Eagles Feed

on:
  schedule:
    - cron: "*/30 * * * *"   # every 30 minutes
  workflow_dispatch: {}       # allow manual run from the Actions tab

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      # Keep credentials so the push works
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run collector
        run: python collect.py

      - name: Commit & push items.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add items.json
          git diff --staged --quiet || git commit -m "chore: update items.json"
          git push