name: Collect news

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 minutes
  workflow_dispatch:
  push:
    paths:
      - "collect.py"
      - "feeds.py"
      - ".github/workflows/collect.yml"

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install feedparser python-dateutil requests

      - name: Run collector
        run: |
          python collect.py
          echo "— items.json summary —"
          python - << 'PY'
          import json, pathlib
          p = pathlib.Path("items.json")
          if not p.exists():
              raise SystemExit("items.json NOT written!")
          d = json.loads(p.read_text(encoding="utf-8"))
          print("items:", len(d.get("items", [])))
          print("sources:", len(d.get("sources", [])))
          print("updated_at:", d.get("updated_at"))
          PY

      - name: Commit items.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add items.json
          git commit -m "Auto update items.json [skip ci]" || echo "No changes"
          git push